"""Vocabularios cerrados del sistema.

Se almacenan en PostgreSQL como ``VARCHAR`` con restricciones ``CHECK`` (ADR-006) y se validan aquí
y en Pydantic. Los estados del estudiante son *interpretaciones operativas* del sistema; nunca se
muestran al estudiante como etiquetas negativas (ver ``STUDENT_FACING_STATE_LABELS``).
"""

from __future__ import annotations

from enum import StrEnum


class Role(StrEnum):
    STUDENT = "STUDENT"
    TEACHER = "TEACHER"
    RESEARCHER = "RESEARCHER"
    ADMIN = "ADMIN"


class UserStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PENDING_CONSENT = "PENDING_CONSENT"
    LOCKED = "LOCKED"
    DISABLED = "DISABLED"


class ConsentParty(StrEnum):
    STUDENT = "STUDENT"
    GUARDIAN = "GUARDIAN"
    INSTITUTION = "INSTITUTION"
    RESEARCHER = "RESEARCHER"


class ConsentStatus(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    DECLINED = "DECLINED"
    REVOKED = "REVOKED"


class LegalDocumentKind(StrEnum):
    PRIVACY_POLICY = "PRIVACY_POLICY"
    TERMS = "TERMS"


class Grade(StrEnum):
    SEVENTH = "7"
    EIGHTH = "8"
    NINTH = "9"


class StudentState(StrEnum):
    NORMAL = "NORMAL"
    EXPLORATION = "EXPLORATION"
    DIFFICULTY = "DIFFICULTY"
    UNCERTAINTY = "UNCERTAINTY"
    IMPULSIVITY = "IMPULSIVITY"
    STAGNATION = "STAGNATION"
    RECOVERY = "RECOVERY"
    AUTONOMY = "AUTONOMY"


STUDENT_FACING_STATE_LABELS: dict[StudentState, str] = {
    StudentState.NORMAL: "En marcha",
    StudentState.EXPLORATION: "Explorando",
    StudentState.DIFFICULTY: "Pensando",
    StudentState.UNCERTAINTY: "Revisando",
    StudentState.IMPULSIVITY: "Rápido",
    StudentState.STAGNATION: "Buscando otro camino",
    StudentState.RECOVERY: "Avanzando",
    StudentState.AUTONOMY: "Con autonomía",
}


class InterventionLevel(StrEnum):
    NONE = "0"
    MICRO_HELP = "1"
    ORIENTATION = "2"
    SCAFFOLDING = "3"
    REPRESENTATION_CHANGE = "4"
    RECOVERY = "5"


class TaskType(StrEnum):
    NUMERIC_PATTERN = "NUMERIC_PATTERN"
    FIGURAL_PATTERN = "FIGURAL_PATTERN"
    TABLE = "TABLE"
    GRAPH = "GRAPH"
    SYMBOLIC = "SYMBOLIC"
    JUSTIFICATION = "JUSTIFICATION"
    TRANSFER = "TRANSFER"


class WorkedExampleType(StrEnum):
    FULL = "FULL"
    PARTIAL = "PARTIAL"
    HIDDEN_STEPS = "HIDDEN_STEPS"
    SELF_EXPLANATION = "SELF_EXPLANATION"
    STRATEGY_COMPARISON = "STRATEGY_COMPARISON"
    INTENTIONAL_ERROR = "INTENTIONAL_ERROR"
    TRANSFER = "TRANSFER"


class Representation(StrEnum):
    VERBAL = "VERBAL"
    NUMERIC = "NUMERIC"
    TABULAR = "TABULAR"
    GRAPHIC = "GRAPHIC"
    SYMBOLIC = "SYMBOLIC"


class ScaffoldType(StrEnum):
    FOCUSING = "FOCUSING"
    GUIDING_QUESTION = "GUIDING_QUESTION"
    HINT = "HINT"
    SELF_EXPLANATION = "SELF_EXPLANATION"
    REPRESENTATION_CHANGE = "REPRESENTATION_CHANGE"
    TASK_DIVISION = "TASK_DIVISION"
    RECOVERY = "RECOVERY"
    METACOGNITIVE = "METACOGNITIVE"
    STRATEGY_COMPARISON = "STRATEGY_COMPARISON"
    ERROR_REFLECTION = "ERROR_REFLECTION"


class InteractionEventType(StrEnum):
    SESSION_STARTED = "SESSION_STARTED"
    TASK_OPENED = "TASK_OPENED"
    EXAMPLE_OPENED = "EXAMPLE_OPENED"
    STUDENT_RESPONSE = "STUDENT_RESPONSE"
    STUDENT_EDITED_RESPONSE = "STUDENT_EDITED_RESPONSE"
    HELP_REQUESTED = "HELP_REQUESTED"
    HELP_OFFERED = "HELP_OFFERED"
    HELP_ACCEPTED = "HELP_ACCEPTED"
    HELP_REJECTED = "HELP_REJECTED"
    HELP_REFORMULATED = "HELP_REFORMULATED"
    STUDENT_REATTEMPT = "STUDENT_REATTEMPT"
    REPRESENTATION_CHANGED = "REPRESENTATION_CHANGED"
    SELF_EXPLANATION = "SELF_EXPLANATION"
    ERROR_DETECTED = "ERROR_DETECTED"
    TEACHER_INTERVENTION = "TEACHER_INTERVENTION"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_ABANDONED = "TASK_ABANDONED"
    SESSION_ENDED = "SESSION_ENDED"


class AuditAction(StrEnum):
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGOUT = "LOGOUT"
    TOKEN_REFRESHED = "TOKEN_REFRESHED"  # noqa: S105
    TOKEN_REUSE_DETECTED = "TOKEN_REUSE_DETECTED"  # noqa: S105
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED"  # noqa: S105
    PASSWORD_RESET = "PASSWORD_RESET"  # noqa: S105
    PASSWORD_CHANGED = "PASSWORD_CHANGED"  # noqa: S105
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DISABLED = "USER_DISABLED"
    ROLE_CHANGED = "ROLE_CHANGED"
    CONSENT_RECORDED = "CONSENT_RECORDED"
    CONSENT_REVOKED = "CONSENT_REVOKED"
    EXPORT_GENERATED = "EXPORT_GENERATED"
    PII_ACCESSED = "PII_ACCESSED"
    RULE_UPDATED = "RULE_UPDATED"
    SCAFFOLD_UPDATED = "SCAFFOLD_UPDATED"
    SETTINGS_UPDATED = "SETTINGS_UPDATED"
    ACCESS_DENIED = "ACCESS_DENIED"


class AuditOutcome(StrEnum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    DENIED = "DENIED"


def values(enum: type[StrEnum]) -> list[str]:
    return [member.value for member in enum]
